### ISSUE TITLE
Todo lists

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [PeanutMelonSeedBigAlmond/PixivFanboxViewer#1]
### Tasks
- [ ] 图片、文件的保存功能
- [ ] 在文章详情页面直接播放视频 / 调用其他播放器播放视频（Uri+ContentProvider）实现
    ![image](https://user-images.githubusercontent.com/25266280/205708333-4e94e15a-c674-4882-a226-c7abeacb17e1.png)
- [ ] fanbox.cc 链接跳转到应用内打开
- [ ] 添加文章类型解析
    - [x] article
    - [x] image  
    - [x] text
    - [ ] ....
- [ ] 用户主页
- [ ] 切换账号 / 退出登录
- [ ] 清除缓存
- [ ] 备份数据
- [ ] Debug: 根据文章ID打开文章详情
### Bugs
- [ ] 加载原图时的进度错误（异常显示为负数）的问题
- [x] 图集查看时，图片index错误问题
